In [1]:
import numpy as np 

X = np.random.rand(4, 2)
y = np.dot(X, np.array([1, 2])) + 3

In [2]:
X.shape, y.shape

((4, 2), (4,))

In [4]:
X, y

(array([[0.8278081 , 0.03411234],
        [0.89768103, 0.96923741],
        [0.3073269 , 0.35795849],
        [0.99816114, 0.6816711 ]]),
 array([3.89603277, 5.83615584, 4.02324387, 5.36150335]))

In [7]:
X = np.hstack([np.ones((X.shape[0], 1)), X])
X.shape

(4, 3)

In [8]:
X_transpose = X.T
theta = np.linalg.inv(X_transpose @ X) @ X_transpose @ y
theta

array([3., 1., 2.])

In [11]:
intercept_ = theta[0]
coef_ = theta[1:]

In [12]:
X @ np.hstack([intercept_, coef_])

array([3.89603277, 5.83615584, 4.02324387, 5.36150335])

In [13]:
y

array([3.89603277, 5.83615584, 4.02324387, 5.36150335])

In [16]:
X_ = np.random.rand(4, 2)
X_ @ coef_

array([0.37152688, 1.27656807, 2.10544053, 1.02367837])

In [15]:
np.linalg.inv(X_.T @ X_) @ X_.T @ y

array([2.29051811, 4.67549029])